var data_dragonfire = [
        {
                name: "THE WASTES OF AN ANCIENT EMPIRE: PROLOGUE",
                en: "The Dessarin Valley.<br/><br/>Stunted brush and thorn-laden vines camouflage ancient foundations and work to reclaim broken towers. Burned land from a recent forest fire leaves charred bones for scavengers to pick through. Over a rise, hunting paths for the Valley's scavengers twist and turn through briar thickets and poisoned berry-brush.<br/><br/>\“Too much blood spilled here.\"<br/><br/>That's the common wisdom, and you don't have to look far for evidence. Eyes watch from the deeper shadows of the wilderness. The carcasses of hunted animals rot next to a stream. In the shadows of the tumbled walls, it takes very little digging to find the remains of bronze shield facings, broken blades, maybe a few ancient coins, and fresh bones. The relics draw scavengers of all races and reasons, and once captured by the Valley, very few seem to make it back out of their own volition.<br/><br/>\"What drew Lord Tellum's son to this godforsaken area?\”<br/><br/>It's a question all of you are asking. Not that the answer really matters. After your heroic stand defending the village, word arrived from local nobility that Christos Tellum, heir to Tellum's Hold up near Waterdeep, was overdue from an excursion through the Valley. Not only Christos, but eight guards, Qellon the Arcane, and Ardin, a local ranger as guide.<br/><br/>\“It would be in our best interest—and your beneficial gain—were you to find the lost party.\"<br/>Duchess Daggerford herself signed the parchment, making it as much an order as a request.<br/>But a single glance into the Valley ahead guarantees one thing: it will be difficult traveling.",
                ko: "데사린 계곡.<br/><br/>억센 덤불과 가시 덩굴들이 부서진 고대의 탑을 뒤덮어, 마치 그 탑을 숨기고 있는 듯 하다. 최근에 있었던 숲의 화재로 불에 탄 땅에은 스케빈저들을 위한 그을린 뼈들이 널려있다. 찔레 덤불과 독이 있는 열매들로 뒤덮힌 계곡의 스케빈저들을 위한 사냥 길을 뚫고 올라가면.<br/><br/>\"여기에는 많은 피가 흘렀군.\"<br/><br/>척 봐도 알 수 있는 일이었다. 황무지의 어두운 그림자 속에는 당신을 지켜보는 눈들이 있고, 사냥당한 동물의 시체들은 시냇물 옆에서 썩고 있다. 무너진 벽의 그림자 아래에서 청동 방패 조각, 부러진 칼날, 몇 개의 고대 동전, 그리고 생긴지 얼마 안 된 뼈의 잔해를 찾는 것은 어렵지 않다. '유물'은 종족과 이유를 불문하고 스케빈저들을 끌어들였고, 한 번 계곡에 발을 들인 자들 중 대부분은 자신의 의지로 돌아가지 못했다.<br/><br/>\"어째서 텔럼경의 아들이 이 신에게 버림받은 곳에 온 거지?\"<br/><br/>모두가 가진 의문이었지만, 그 답은 중요하지 않았다.  당신이 마을을 지키는 영웅적인 활약을 한 뒤, 워터딥 근처 텔럼 성채의 후계자인 크리스토스 텔럼에 대한 소식이 전해졌다. 그와 8명의 가드, 비전술사 퀠른 그리고 순찰자인 아딘으로 이루어진 일행은 이미 계곡을 지나 목적지에 도착했었어야 했다.<br/><br/>\"서둘러 그들을 찾아야 합니다. 보상은 충분히 하겠어요.\" 대거포드의 여공작은 직접 양피지에 서명하며, 사실상 명령이나 다름 없는 부탁을 했다. 눈 앞에 놓인 계곡을 보면 확실한 것은 하나 있다. 그것은 이 여행이 쉽지 않을 것이라는 것이다."
        },
        {
                name: "THE WASTES OF AN ANCIENT EMPIRE: EPILOGUE",
                en: "As the final body falls, its blood staining the ground dark, a long figure crashes its way through nearby brush and briars. Sword in hand, it staggers forward, rocking from side to side as if to a chant only it can hear. Tired arms brandish weapons. Fresh spells hover on lips. As Lord Tellum's son and heir all but falls into your arms.<br/><br/>\"Mine! And make no mistake about it!\"<br/><br/>His once-rich clothing now hangs in tatters, and his face is drawn and haggard. If he's slept in the past three days, it wasn't for long. In one hand he grips what appears to be a simple iron flask. With his other, he slashes a sword in your direction, but there's no strength behind it. Doubt clouds his eyes for a moment, and he lowers the blade.<br/><br/>\"No. Not bandits. No. Did he send you? Duchess Daggerford? Or... my father? Mine, tell them..\"<br/><br/>It's the last coherent sentence he forms. And, dropping his sword in the battlefield’s gore, he collapses.Gathered around the young noble, muscles still aching from the recent battle, there seems little you can do except to make camp and watch over him. The valley seems safe enough—at the moment—for a small fire and a rest. Today, at least, your actions have made the difference. And tomorrow will take care of tomorrow.<br/><br/>Still, the young lord's last word echoes in your head: \"..mine.\"",
                ko: "마지막 적이 쓰러지며 그것의 피가 땅을 검게 물들이는 순간, 긴 형체 하나가 근처의 덤불과 찔레가시를 뚫고 나왔다. 그것은 비틀거리며 움직이고 있었고, 손에 든 검은 마치 주문을 외는 듯 좌우로 흔들리고 있다. 지친 팔로 무기를 휘두르고, 새로운 주문이 입술에 맴돈다. 텔럼 경의 아들이자 후계자인 그는 당신의 팔에 안겼다.<br/><br/>\"이건 내꺼다! 허튼 생각하지 마!\"<br/><br/> 원래는 고급스러웠던 것이 분명한 그의 옷은 이제 넝마가 되어 있었고, 그의 얼굴은 핼쑥하고 초췌하다. 마치 3일은 잠을 못 잔 듯 하다. 그는 한 손에 단순한 모양의 철제 플라스크를 쥐고 있었고 다른 한 손으로는 당신을 향해 검을 휘두르고 있었지만, 팔에 힘이 없어 위협이 되지 않았다. 잠시 의심의 눈초리로 당신을 보던 그는 곧 검을 내렸다.<br/><br/>\"아니. 도적은 아니군. 누군가 너희를 보냈나? 대거포드의 여공작? 아니면 아버지? 이건 내꺼야. 그들에게 전해...\"<br/><br/> 이 말을 마지막으로 그는 검을 떨어뜨리며 전장의 시체들 위에 쓰러졌다. 격렬한 전투의 후유증으로 근육이 아파왔지만, 당신은 쓰러진 젊은 귀족의 주변을 정리했다. 당장 당신이 할 수 있는 일은 캠프를 만들고 그를 지켜보는 것 밖에 없는 듯 하다. 적어도 당장은 작은 모닥불을 피우고 휴식을 취할 수 있을 만큼 안전해 보인다. 어쨋든 오늘은 헛수고를 하진 않은 것 같다. 내일 일은 내일 걱정하는게 나으리라. <br/><br/>계속해서 젊은 후계자의 마지막 말이 당신의 머리속에 울려 퍼진다. \"...이건 내꺼야\""
        },
];

/*
{
                        name: "",
                        en: "",
                        ko: ""
                },
*/